SET SCRIPTDIR=%~dp0
SET ASSETS_SRC=%SCRIPTDIR%assets_original
SET ASSETS_DST1=%~1\assets
SET ASSETS_DST2=%SCRIPTDIR%..\additional\assets
IF NOT EXIST "%ASSETS_DST1%\NUL" MKDIR "%ASSETS_DST1%"
ROBOCOPY "%ASSETS_SRC%" "%ASSETS_DST1%" /XF .gitignore /XD .git /E
IF %ERRORLEVEL% GTR 3 GOTO fail
IF NOT EXIST "%ASSETS_DST2%\NUL" MKDIR "%ASSETS_DST2%"
ROBOCOPY "%ASSETS_SRC%" "%ASSETS_DST2%" /XF .gitignore /XD .git /E
IF %ERRORLEVEL% GTR 3 GOTO fail

exit /b 0

:fail
exit /b 1

